[package]
name = "chown"
version = "0.1.0"
authors = ["Tanner Babcock <babkock@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
libc = "0.2"
glob = "0.3.0"
walkdir = "2.2"
assert_cli = "0.6.3"

