[package]
name = "cat"
version = "0.1.0"
authors = ["Tanner Babcock <babkock@gmail.com>"]
edition = "2018"

[dependencies]
quick-error = "1.2.2"
clap = "2.33.0"

[target.'cfg(unix)'.dependencies]
unix_socket = "0.5.0"

